### ISSUE TITLE
Config Initialization

### ISSUE THREAD

**Issue by ghost** [sylv1b/cronGuru#2]
Having issues getting this to run. 

How should the username & password be entered into the config file?

When not entering credentials into the config:
``` 
chase@macOS57P3 cronGuru % npm run get-token

> @sylbro/cronguru@1.0.2 get-token
> node src/getToken.js

start login
/Users/chase/.cronGuru/cronGuru/src/calls.js:9
    const { email, password } = config.login;
                                ^

ReferenceError: Cannot access 'config' before initialization
    at login (/Users/chase/.cronGuru/cronGuru/src/calls.js:9:33)
    at getToken (/Users/chase/.cronGuru/cronGuru/src/getToken.js:4:29)
    at Object.<anonymous> (/Users/chase/.cronGuru/cronGuru/src/getToken.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.7.0
```

When entering the credentials into the config:
![Scrn2023-02-27-000236@2x](https://user-images.githubusercontent.com/10358634/221639260-486ba184-591c-408e-a015-e0334d3bec36.png)
```
chase@macOS57P3 cronGuru % npm run get-token

> @sylbro/cronguru@1.0.2 get-token
> node src/getToken.js

start login
/Users/chase/.cronGuru/cronGuru/src/calls.js:9
    const { email, password } = config.login;
                                ^

ReferenceError: Cannot access 'config' before initialization
    at login (/Users/chase/.cronGuru/cronGuru/src/calls.js:9:33)
    at getToken (/Users/chase/.cronGuru/cronGuru/src/getToken.js:4:29)
    at Object.<anonymous> (/Users/chase/.cronGuru/cronGuru/src/getToken.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.7.0
```

**Comment by StefanescuCristian** [comment]
Hi @Mr1mpossible , I'm having the same trouble. Did you have any success running this?
